added draft custom harness creation doc
vijilAI/docs pull request #20
Opened 2024-06-17 16:30 UTC by boltzmann-brain

Per discussion, added draft topic on how to create a custom harness, assuming ideal user experience

Also fixed broken link elsewhere

2024-06-17 20:49 UTC, shubhobm commented on source/python-sdk/structure/custom-harness.md
> +client.Harnesses.create(name="my custom harness", probes=["probe1", "probe2"])
let's do `client.harnesses.*` and `client.evaluations.*`
I'll roll in changes in the python client

2024-06-17 20:49 UTC, shubhobm requested changes
small changes

2024-06-17 20:49 UTC, shubhobm commented on source/python-sdk/structure/custom-harness.md
> +client.Harnesses.delete(name="my custom harness")
`client.harnesses.*`

2024-06-18 13:39 UTC, boltzmann-brain commented
@shubhobm changed casing as requested

2024-06-18 13:49 UTC, shubhobm approved these changes
Lgtm

2024-06-18 14:17 UTC, merged